### ISSUE TITLE
ExtensionCallMarklogic fails to send an input body

### ISSUE THREAD

**Issue by Audarth** [marklogic-community/marklogic-nifi-incubator#23]
It seems most of the time if you're using ExtensionCallMarklogic to send an input in the body to a PUT or POST extension the body of the request doesn't get read properly.

I've identified a switch statement that might be the cause.

**Comment by janmichaelyu** [comment]
Hi @Audarth the changes look good. Could you also update the ExtensionCallMarkLogicTest with tests that reflect your changes?

**Comment by Audarth** [comment]
Hi,

Those unit tests are still pending but I very strongly recommend this should be merged asap since I've just come across a 2nd project that's being negatively impacted by it.

**Comment by sjiang99** [comment]
Fixed in PR #26
