### ISSUE TITLE
Recipe for DHF 4.x Harmonize flow integration with NiFi

### ISSUE THREAD

**Issue by jmamanpara** [marklogic-community/marklogic-nifi-incubator#33]
Based on DHF Tutorial available at https://marklogic.github.io/marklogic-data-hub/tutorial/4x/
Prepare the template and documentation to invoke the DHF Harmonize flow from Apache NiFi using EvaluateCollector Processor.

**Comment by sjiang99** [comment]
https://marklogic-community.github.io/marklogic-nifi-incubator/run-data-hub-harmonize-flow.html
