### ISSUE TITLE
Recipe for DHF 4.x (Input + Harmonize flow) integration with NiFi

### ISSUE THREAD

**Issue by jmamanpara** [marklogic-community/marklogic-nifi-incubator#34]
Based on DHF Tutorial available at https://marklogic.github.io/marklogic-data-hub/tutorial/4x/
Prepare the template and documentation to invoke the DHF Input and Harmonize flow from same template using Apache NiFi

**Comment by sjiang99** [comment]
https://marklogic-community.github.io/marklogic-nifi-incubator/run-data-hub-flows.html
