### ISSUE TITLE
Review fix for NiFi 1.9.x data loss and upgrade to 1.10 or 1.9.3 as appropriate

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-nifi-incubator#37]
We are not upgrading pending resolution of this critical bug:

https://issues.apache.org/jira/browse/NIFI-6215

This ticket is to track and evaluate the next step

**Comment by janmichaelyu** [comment]
https://issues.apache.org/jira/browse/NIFI-6215 has been resolved and will be part of Apache NiFi 1.10.
