### ISSUE TITLE
Expand expression language scope for ExtensionCallMarkLogic's dynamic properties

### ISSUE THREAD

**Issue by brent-hartwig** [marklogic-community/marklogic-nifi-incubator#49]
Same request as https://github.com/marklogic-community/marklogic-nifi-incubator/issues/48 but for the `ExtensionCallMarkLogic` processor instead of the `PutMarkLogic` processor.  The former is used to initiate harmonization while the latter is used to initiate ingestion.  The data hub flow name will vary by the input being processed.  Thank you.

**Comment by dmcassel** [comment]
I'm going to need to work around the lack of this capability. I can either use an `InvokeHTTP` or skip the resource and use `ExecuteScriptMarkLogic`. Would be much nicer to use `ExtensionCallMarkLogic` here.

**Comment by dmcassel** [comment]
Just had another case where I wanted to set an extension parameter based on a flowfile attribute.

**Comment by rjrudin** [comment]
@brent-hartwig  @dmcassel  I did a manual test of this against 1.9.1.5-SNAPSHOT in marklogic/nifi, which is based off the 1.9.1.4 incubator release, and ExtensionCallML has not been modified. The manual test worked, and then I add an automated test (and did a little refactoring) in https://github.com/marklogic/nifi/commit/fe966842113752e1f4bf06f974694aad9888abca to verify it. 

Below is a screenshot from my manual test - this is using the "replay" extension in src/test/ml-modules in the processors project, which looks for the "replay" parameter. 

![image](https://user-images.githubusercontent.com/5026193/105656708-dbbf9700-5e90-11eb-98a4-86d809a9ba41.png)

If you can provide an example of this not working, please open a ticket in marklogic/nifi for it.
