### ISSUE TITLE
Set attribute for DHF options JSON in PutMarkLogic

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/marklogic-nifi-incubator#50]
PutMarkLogic (PML) already sets a "URIs" attribute after it ingests a WriteBatch. 

It would be handy also set an "optionsJson" attribute that included the URIs in an option block as required by the DHF ml:runFlow endpoint - https://docs.marklogic.com/datahub/flows/run-flow-using-rest-client-api.html . This would allow for the next processor in the flow to make a call to that DHF endpoint without having to prepare the options JSON object.

Otherwise, an ExecuteScript processor must be used with some ugly JS code to construct this JSON block. The JS code looks like this:

```
var flowFile = session.get();
if (flowFile != null) {
  var StreamCallback =  Java.type("org.apache.nifi.processor.io.StreamCallback")
  var IOUtils = Java.type("org.apache.commons.io.IOUtils")
  var StandardCharsets = Java.type("java.nio.charset.StandardCharsets")
  var optionsJson;
  flowFile = session.write(flowFile, new StreamCallback(function(inputStream, outputStream) {
    //var text = IOUtils.toString(inputStream, StandardCharsets.UTF_8);
    var text = flowFile.getAttribute("URIs");
    var newObj = {"uris": text.split(",")};
    optionsJson = JSON.stringify(newObj, null, '\t');
    outputStream.write(optionsJson.getBytes(StandardCharsets.UTF_8));
  }));
  flowFile = session.putAttribute(flowFile, "optionsJson", optionsJson);
  session.transfer(flowFile, REL_SUCCESS)
}
```

Note that this would just work for PutMarkLogicRecord as well, since that extends PutMarkLogic.

**Comment by jmamanpara** [comment]
Implemented and merge with ml-develop as part of PR #54
