### ISSUE TITLE
Remove EvaluateCollectorMarkLogic

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/marklogic-nifi-incubator#51]
This processor should not have been created - I was not aware of /v1/internal/hubcollector at the time. And it only works for DHF 4. If a client wants to perform this functionality, they can just use InvokeHttp to hit /v1/internal/hubcollector, which avoids the security issues associated with evaluating scripts.

**Comment by sjiang99** [comment]
The DHF endpoints are internal endpoints, also they differ from DHF 4 to DHF 5. We have refactor the EvaluateCollectorMarkLogic to work with both versions. See:
https://github.com/marklogic-community/marklogic-nifi-incubator/issues/42
