### ISSUE TITLE
Use mock service for unit tests

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/marklogic-nifi-incubator#53]
I'm working on revising PutMarkLogic as described in #25. The unit tests are proving to be an obstacle for me, as PutMarkLogicTest doesn't call `onScheduled`, so some things don't get initialized. My revisions need that initialization. Is the reason for calling `processor.onTrigger` rather than `TestRunner.run()` to avoid talking to an actual MarkLogic instance? Seems like a good place for a Mock service. Is there a reason why that isn't being done?

**Comment by jmamanpara** [comment]
@dmcassel can you please confirm if this has been implemented along with #25 fix? Thanks.

**Comment by dmcassel** [comment]
It has not been done to the best of my knowledge.

**Comment by rjrudin** [comment]
@dmcassel  I recommend closing this, as my experience has been that we really want to use TestRunner and talk to ML as much as possible, as those simulates reality as best as possible. Any test that doesn't do that should be considered a true unit test that is just e.g. testing the logic in a protected method.

**Comment by dmcassel** [comment]
@rjrudin good points; I agree with closing
