### ISSUE TITLE
Include file required for NiFi Registry bundle upload

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/marklogic-nifi-incubator#77]
NiFi Registry allows for uploading NARs, in addition to saving flows. This would make deployments easier. [One of the requirements for doing this is](https://nifi.apache.org/docs/nifi-registry-docs/html/user-guide.html#upload-bundle): 

> In order to upload a NAR to NiFi Registry, it must contain the file META-INF/docs/extension-manifest.xml which is produced by the NAR Maven plugin, starting with version 1.3.0.

RFE: add the required manifest file to the NAR files so that we can upload them as NiFi Registry bundles.

**Comment by sjiang99** [comment]
I have updated the 2 nar files in the release with the required manifest files.
