### ISSUE TITLE
Large Query Result Set Results in no processor activity

### ISSUE THREAD

**Issue by millerbill3** [marklogic-community/marklogic-nifi-incubator#87]
Per customer observation, if the query returns a very large number of records (i.e. 500K or so) batching is not happening and the user fails to get any results. This issue became apparent after the fix for issue #83 was completed.

User's original email:

> When I have my query pulling about 500 documents, it runs and returns data.  However, when I run a query pulling over 500,000 documents.  It doesn't seem to run.  I started the process and let it run for 30 minutes.  I don't see any results returned in the queue.  With version 1.8, it returns chunk of data at a time, so I start seeing partial set of data after few minutes.

The 1.8 reference is referring to the 1.8 version of the MarkLogic NiFi NARs.

**Comment by rjrudin** [comment]
I did a quick test of 50k and then 500k records, and everything worked fine. That was just running NiFi and ML on my laptop, which of course isn't a recommended setup (I did get an out-of-memory error on a subsequent test, but again - don't run NiFi and ML on your laptop :) ). 

There's nothing actionable about this ticket, so if you are able to reproduce it, please create a ticket in the marklogic/nifi project with details on how to reproduce it.
