### ISSUE TITLE
Possible Memory Leak in QueryRowsMarkLogic.java

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic-community/marklogic-nifi-incubator#99]
https://github.com/marklogic-community/marklogic-nifi-incubator/blob/903a7f1f7b1ef761c9f1e1931475c3609fb14c99/nifi-nar-bundles/nifi-marklogic-bundle/nifi-marklogic-processors/src/main/java/org/apache/nifi/marklogic/processor/QueryRowsMarkLogic.java#L84

My customer claims they've observed a memory leak in this processor caused by not closing an InputStream.

Customer rebuilt the project using by replacing the if block with this and claims it was fixed:

```
InputStreamHandle handle = new InputStreamHandle();
if( handle != null) {
  try {
     InputStream inputStream = rowManager.resultDoc(plan, handle.withMimetpe(mimeType)).get();
     if (inputStream != null) { 
       flowFile = session.write(flowFile, out -> { 
          IOUtils.copy(inputStream, out);
       });
     }
  } finally {
     handle.close();
  }
}
```
Before submitting a PR on their behalf I just wanted to vet their finding.

**Comment by rjrudin** [comment]
Looks like IOUtils is not closing the InputStream, so yeah, it needs to be closed.

Can you submit the PR to marklogic/nifi though? That is being supported, and the same issue is there.

**Comment by RobertSzkutak** [comment]
Thanks! Closing this and will submit to the other project.
